name: Build Docs

on:
  push:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pages: write
      id-token: "write"

    steps:
      - name: Checkout SIMPLE
        uses: actions/checkout@v4
        with:
          path: simple

      - name: Checkout SIMPLE Docs
        uses: actions/checkout@v4
        with:
          repository: germolinal/simple_docs
          token: ${{ secrets.SIMPLE_DOCS_WRITE_TOKEN }}
          path: simple_docs

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

        # The runs in parallel/release create the validation results.
        # The run `cargo test -p model` writes the IOReference.
      - name: Run tests parallel
        run: |
          cargo test --manifest-path simple/Cargo.toml -p model

        # cargo test --manifest-path simple/Cargo.toml --release --features parallel --verbose --workspace
        # cargo test --manifest-path simple/Cargo.toml --release --features parallel --verbose -p simple -- --ignored

      - name: Copy documentation
        run: |
          echo ${{ secrets.SIMPLE_DOCS_WRITE_TOKEN }}
          rm -rf simple_docs/auto_src/*
          cp -rf simple/docs simple_docs/auto_src/docs
          mkdir  simple_docs/auto_src/model
          cp -rf simple/model/tests simple_docs/auto_src/model/tests

      - name: Push docs
        run: |
          cd simple_docs
          git add .
          git commit -m 'automatic documentation update'
          git push
