name: Build Docs

on:  
  push:
    branches: [ main ]  

env:
  CARGO_TERM_COLOR: always

jobs:    
  # This is the one we use for producing documentation
  test_parallel:
    runs-on: ubuntu-latest  
    permissions:
      contents: 'read'
      id-token: 'write'   

    steps:
    - uses: actions/checkout@v3   

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

      # The runs in parallel/release create the validation results.
      # The run `cargo test -p model` writes the IOReference.
    - name: Run tests parallel
      run: |        
        cargo test --release --features parallel --verbose --workspace 
        cargo test --release --features parallel --verbose -p simple -- --ignored 
        cargo test -p model
    
    - name: Install MdBook
      run: cargo install mdbook

    - name: Install MDBook Katex
      run: cargo install mdbook-katex

    - name: Build mdbook
      run: mdbook build ./docs/ioreference

    # - name: Setup Pages
    #   uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload Docs
        path: './docs'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
