name: Release

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout SIMPLE
        uses: actions/checkout@v4
        with:
          path: simple

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests parallel
        run: |
          cargo test --manifest-path simple/Cargo.toml --features parallel --workspace
          cargo test --manifest-path simple/Cargo.toml --release --features parallel -p simple -- --ignored
          cargo test --manifest-path simple/Cargo.toml -p model

      - name: Checkout SIMPLE Docs
        uses: actions/checkout@v4
        with:
          repository: germolinal/simple_docs
          token: ${{ secrets.SIMPLE_DOCS_WRITE_TOKEN }}
          path: simple_docs

      - name: Copy documentation
        run: |
          rm -rf simple_docs/auto_src/*
          cp -rf simple/docs simple_docs/auto_src/docs
          mkdir  simple_docs/auto_src/model
          cp -rf simple/model/tests simple_docs/auto_src/model/tests

      - name: Push docs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          cd simple_docs
          git add auto_src
          git commit -m 'automatic documentation update'
          git push

  publish_binaries:
    needs: test_and_docs

    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      pages: write
      id-token: "write"

    strategy:
      fail-fast: false
      matrix:
        target:
          [
            aarch64-apple-darwin,
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc,
          ]

    steps:
      - name: Checkout SIMPLE
        uses: actions/checkout@v4
        with:
          path: simple

      - name: Checkout SIMPLE Docs
        uses: actions/checkout@v4
        with:
          repository: germolinal/simple_docs
          token: ${{ secrets.SIMPLE_DOCS_WRITE_TOKEN }}
          path: simple_docs

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Target ${{matrix.target}}
        run: |
          rustup target add ${{matrix.target}}
          sudo apt install -y zip

      - name: Compile for target ${{matrix.target}}
        run: |
          cargo build --manifest-path simple/Cargo.toml --release --features parallel --target ${{matrix.target}}

      - name: Remove intermediate files in ${{matrix.target}}
        run: |
          find target/${{matrix.target}}/release -type f -name "*.d" -delete
          rm -rf simple/target/${{matrix.target}}/release/.fingerprint
          rm -rf simple/target/${{matrix.target}}/release/build
          rm -rf simple/target/${{matrix.target}}/release/deps
          rm -rf simple/target/${{matrix.target}}/release/examples
          rm -rf simple/target/${{matrix.target}}/release/incremental
          rm -rf simple/target/${{matrix.target}}/release/.cargo-lock
          rm -rf simple/target/${{matrix.target}}/release/*.rlib

      - name: Zip binaries for ${{matrix.target}}
        run: |
          zip -r simple_docs/dist/binaries/${{matrix.target}}.zip simple/target/${{matrix.target}}/release

      - name: Push binaries
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          cd simple_docs
          git add dist/binaries
          git commit -m 'automatic update of target ${{matrix.target}}'
          git push

  check_default:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/checkout@v4
      - name: Run tests default
        run: |
          cargo check --workspace

  check_float:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/checkout@v4
      - name: Check float
        run: cargo check --features float --workspace

  check_float_parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/checkout@v4
      - name: Check float parallel
        run: cargo check --features float --features parallel --workspace
